on:
  push:
    branches:
      - main

jobs:
  process-files:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Fetch full Git history

      - name: Update Title, Tags, Formatting, and Replace Links
        run: |
          # Function to replace blog links with runs.lol links and strip .html
          replace_blog_links() {
            for file in $(git diff --name-only HEAD~1 HEAD | grep '.md' | grep -v '^static-pages/'); do
              echo "Replacing links in $file..."
              sed -E -i "s~https://ericmwalk\.blog/([0-9]{4}/[0-9]{2}/[0-9]{2}/[^) \"']+)(\.html)?~https://runs.lol/\1~g" "$file"
            done
          }

          for file in $(git diff --name-only HEAD~1 HEAD | grep '.md' | grep -v '^static-pages/'); do
            echo "Processing $file..."

            # Process Title
            if grep -q '^title:' "$file"; then
              title_line=$(grep '^title:' "$file")
              title_value="$(echo "$title_line" | sed 's/^title: //; s/"//g')"
              sed -i '/^title:/d' "$file"  # Remove the title line
            else
              title_value=""
            fi

            # Process Tags
            if grep -q '^tags:' "$file"; then
              echo "Updating tags format..."
              awk '
                BEGIN {inside_tags=0; tags=""}
                /^tags:/ {inside_tags=1; next}
                inside_tags && /^[[:space:]]*- / {sub(/^[[:space:]]*- /, ""); tags = tags ? tags ", " $0 : $0; next}
                inside_tags {inside_tags=0; print "tags: " tags}
                {print}
              ' "$file" > temp && mv temp "$file"
            fi

            # Ensure Blank Line After YAML Front Matter
            awk '
              BEGIN {found = 0}
              {print $0}
              /^---$/ {
                found++;
                if (found == 2) print "";  # Add blank line after the second ---
              }
            ' "$file" > temp && mv temp "$file"

            # Insert Title if Available
            if [ -n "$title_value" ]; then
              awk -v title="# $title_value" '
                BEGIN {found = 0}
                {print $0}
                /^---$/ {found++}
                found == 2 && !title_inserted {
                  print ""; print title; title_inserted=1;  # Add title after blank line
                }
              ' "$file" > temp && mv temp "$file"
            fi
          done

          # Replace Blog Links
          replace_blog_links

      - name: Commit Changes
        run: |
          git config --global user.name "ericmwalk"
          git config --global user.email "eric@brebs.net"
          git add .
          git diff --cached --quiet || git commit -m "Updated title, tags, and replaced blog links in updated files"
          git push

  weblog_import:
    runs-on: ubuntu-latest
    needs: process-files
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Pull Latest Changes
        run: |
          git pull origin main

      - name: Debug Repository State
        run: git log --oneline -5

      - id: weblog_import
        uses: neatnik/weblog.lol@v1
        env:
          ADDRESS: ericmwalk
          WEBLOG_API_KEY: ${{ secrets.WEBLOG_API_KEY }}
