  weblog_import:
    runs-on: ubuntu-latest
    needs: process-files
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Fetch full Git history

      - name: Merge Open Pull Request
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # Find the first open pull request and merge it
          pr_number=$(gh pr list --state open --json number --jq '.[0].number')
          if [ -n "$pr_number" ]; then
            echo "Merging pull request #$pr_number..."
            gh pr merge $pr_number --merge --admin
          else
            echo "No open pull requests to merge."
          fi

      - name: Pull Latest Changes
        run: |
          # Configure your username and email
          git config --global user.name "Your Name"
          git config --global user.email "your-email@example.com"
          
          git pull --no-rebase origin main  # Use merge strategy

      - name: Debug Repository State
        run: git log --oneline -5

      - id: weblog_import
        uses: neatnik/weblog.lol@v1
        env:
          ADDRESS: ericmwalk
          WEBLOG_API_KEY: ${{ secrets.WEBLOG_API_KEY }}
