on:
  push:
    branches:
      - main

jobs:
  process-files:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Fetch full Git history
      - name: Remove Title Line
        run: |
          for file in $(git diff --name-only HEAD~1 HEAD | grep '.md'); do
            echo "Processing $file..."
            sed -i '/^title:/d' "$file"
          done
      - name: Commit Changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add .
          git diff --cached --quiet || git commit -m "Removed title line from updated files"
          git push

  weblog_import:
    runs-on: ubuntu-latest
    needs: process-files  # Ensure this runs after process-files
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Pull Latest Changes
        run: |
          git pull origin main  # Pull the latest changes from the main branch

      - name: Debug Repository State  # (Optional, but helpful for debugging)
        run: git log --oneline -5
      - id: weblog_import
        uses: neatnik/weblog.lol@v1
        env:
          ADDRESS: ericmwalk
          WEBLOG_API_KEY: ${{ secrets.WEBLOG_API_KEY }}
