on:
  push:
    branches:
      - main
      
jobs:
  process-files:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Fetch full Git history
      - name: Process Title Line
        run: |
          for file in $(git diff --name-only HEAD~1 HEAD | grep '.md'); do
            echo "Processing $file..."
            title=$(head -n 1 "$file")
            sed -i '1d' "$file"  # Remove the title line
            sed -i '/^---$/a # '$title' '$file"  # Add title after the second '---' with a space after '#'
          done
      - name: Commit Changes
        run: |
          git config --global user.name "ericmwalk"
          git config --global user.email "eric@brebs.net"
          git add .
          git diff --cached --quiet || git commit -m "Moved title line to body in updated files"
          git push

  weblog_import:
    runs-on: ubuntu-latest
    needs: process-files  # Ensure this runs after process-files
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Pull Latest Changes
        run: |
          git pull origin main  # Pull the latest changes from the main branch

      - name: Debug Repository State  # (Optional, but helpful for debugging)
        run: git log --oneline -5
      - id: weblog_import
        uses: neatnik/weblog.lol@v1
        env:
          ADDRESS: ericmwalk
          WEBLOG_API_KEY: ${{ secrets.WEBLOG_API_KEY }}
