# This workflow will remove the title section of the files published if there is not anything after the title.
name: Remove title section if empty
on:
  push:
    branches:
      - master
jobs:
  remove_title_section:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - run: pip install toml
      - run: python scripts/remove_title_section.py
