name: Remove Empty Titles

on:
  push:
    branches:
      - main

jobs:
  clean_empty_titles:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyyaml

      - name: Remove empty titles from files
        run: |
          #!/usr/bin/env python3
          import os
          import yaml

          # Path to the directory where the files are located
          content_dir = os.getcwd()

          for root, _, files in os.walk(content_dir):
              for file in files:
                  if file.endswith(".md") or file.endswith(".yaml"):
                      file_path = os.path.join(root, file)

                      with open(file_path, 'r') as f:
                          content = f.read()

                      if 'title:' in content:
                          lines = content.splitlines()
                          new_lines = []
                          for line in lines:
                              if line.strip().startswith('title:') and line.strip() == 'title:':
                                  continue  # Skip this line if empty title
                              new_lines.append(line)

                          new_content = "\n".join(new_lines)

                          with open(file_path, 'w') as f:
                              f.write(new_content)

      - name: Commit changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "Remove empty title fields"
          git push
        continue-on-error: true
