on: [push]

jobs:
  process-files:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Fetch full Git history

      - name: Remove Title Line
        run: |
          for file in $(git diff --name-only HEAD~1 HEAD | grep '.md'); do
            echo "Processing $file..."
            sed -i '/^title:/d' "$file"
          done

      - name: Commit Changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add .
          git diff --cached --quiet || git commit -m "Removed title line from updated files"
          git push

      - name: Debug Repository State
        run: git log --oneline -5

  weblog_import:
    runs-on: ubuntu-latest  # Corrected indentation
    needs: process-files    # Ensure this runs after process-files
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Fetch full Git history

      - name: Install GitHub CLI
        run: sudo apt-get install gh -y

      - name: Authenticate GitHub CLI
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh auth login --with-token <<< "${{ secrets.GITHUB_TOKEN }}"

      - name: Merge Open Pull Request
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # Find the first open pull request and merge it
          pr_number=$(gh pr list --state open --json number --jq '.[0].number')
          if [ -n "$pr_number" ]; then
            echo "Merging pull request #$pr_number..."
            gh pr merge $pr_number --merge --admin
          else
            echo "No open pull requests to merge."
          fi

      - name: Pull Latest Changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git pull origin main  # Ensure the latest changes are pulled
