name: Remove Title Line

on:
  push:
    paths:
      - '*.md' # Adjust the file pattern if needed

jobs:
  remove_title:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Remove title line
        run: |
          sed -i '/^title:/d' *.md # Adjust the file pattern if needed

      - name: Commit changes
        run: |
          git config user.name 'github-actions[bot]'
          git config user.email '41898282+github-actions[bot]@users.noreply.github.com'
          git commit -am "Remove title line"

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
