name: Remove Title Line

on:
  push:
    paths:
      - "**/*.md" # Adjust this pattern for your file types or directories

jobs:
  process-files:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install dependencies
        run: npm install js-yaml

      - name: Process Markdown files
        run: |
          node <<EOF
          const fs = require('fs');
          const path = require('path');
          const yaml = require('js-yaml');

          const files = fs.readdirSync('./').filter(f => f.endsWith('.md'));
          files.forEach(file => {
            const content = fs.readFileSync(file, 'utf8');
            const match = content.match(/^---[\\s\\S]*?---/);
            if (match) {
              const frontMatter = yaml.load(match[0].slice(3, -3)); // Load YAML
              const updatedFrontMatter = Object.entries(frontMatter).filter((['But title'] != title).replace in the passed write }
